### ISSUE TITLE
大佬能更新一下数据吗，谢谢

### ISSUE THREAD

**Issue by yhld456** [adyliu/china_area#10]

**Comment by adyliu** [comment]
已更新至2021年

**Comment by yhld456** [comment]
非常感谢

**Comment by kaoson** [comment]
不全啊，深圳大鹏新区都没有

**Comment by bg4hkq** [comment]
> 不全啊，深圳大鹏新区都没有
按照咱民政部公布2021年5月10日最新的区划里也灭有大鹏呀，可能是不是还没有上报民政部那边报批呀，这个涉及统一口径问题，大佬也不敢下更新，还是以官方数据为基础嘛
http://www.mca.gov.cn/article/sj/xzqh/1980/202105/20210500033655.shtml

**Comment by xiangyuecn** [comment]
别说大鹏新区了（地理位置应该是在龙岗区还是哪个区），雄安新区、天府新区也没有的，这些都是行政管理区，和行政区划是有区别的，所以没有是正常的😁

欢迎使用我的一个类似的库： https://github.com/xiangyuecn/AreaCity-JsSpider-StatsGov 数据比较全，另外采集了坐标边界数据😊
