### ISSUE TITLE
readme上县、镇、村的数量跟我爬下来的数量不一致诶，但总数又一样

### ISSUE THREAD

**Issue by linganmin** [adyliu/china_area#21]
![image](https://user-images.githubusercontent.com/17434123/224625505-0b074df0-c838-4895-bc51-7e8846b96f38.png)

我爬下来的总数：664486
![image](https://user-images.githubusercontent.com/17434123/224625732-85baaaf8-63f6-4e54-80e3-fbd16edf5910.png)

**Comment by adyliu** [comment]
注意东莞市下面没有3级县，直接下级有4级 石龙镇、5级东城街道。

http://www.stats.gov.cn/tjsj/tjbz/tjyqhdmhcxhfdm/2022/44/4419.html

**Comment by linganmin** [comment]
> 注意东莞市下面没有3级县，直接下级有4级 石龙镇、5级东城街道。
> 
> http://www.stats.gov.cn/tjsj/tjbz/tjyqhdmhcxhfdm/2022/44/4419.html

嗯嗯 那天发现了，感谢大佬
